//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RHServerManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RHServerManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server code=&quot;800&quot; agent=&quot;1&quot; world=&quot;10101&quot; name=&quot;agent_server&quot; private_ip=&quot;PRIVATE_IP&quot; private_port=&quot;51060&quot; public_ip=&quot;&quot; public_port=&quot;0&quot; public_udpport=&quot;0&quot; thread_num=&quot;2&quot; session_count=&quot;10&quot; debug=&quot;0&quot; ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; /&gt;
        ///&lt;agentmanager ip=&quot;PRIVATE_IP&quot; port=&quot;51091&quot; code=&quot;900&quot; send_time_second=&quot;5&quot; /&gt;
        ///&lt;db_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51055&quot; code=&quot;1&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;db_log_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51056&quot; code=&quot;2&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;msg_server ip=&quot;PRIVATE_IP&quot; port=&quot;510 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string agent {
            get {
                return ResourceManager.GetString("agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server code=&quot;800&quot; agent=&quot;1&quot; world=&quot;10101&quot; name=&quot;AGENT_800&quot; private_ip=&quot;PRIVATE_IP&quot; private_port=&quot;51060&quot; public_ip =&quot;&quot; public_port=&quot;0&quot; public_udpport=&quot;0&quot; thread_num=2 session_count=10 debug=&quot;0&quot;/&gt;
        ///&lt;agentmanager ip=&quot;PRIVATE_IP&quot; port=&quot;51091&quot; code=&quot;900&quot; send_time_second=&quot;5&quot; /&gt;
        ///
        ///&lt;db_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51055&quot; code=&quot;1&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;db_log_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51056&quot; code=&quot;2&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;msg_server ip=&quot;PRIVATE_IP&quot; port=&quot;51052&quot; code=&quot;61&quot; /&gt;
        ///&lt;gm_server ip=&quot;PRI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AGENT_800 {
            get {
                return ResourceManager.GetString("AGENT_800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server code=&quot;800&quot; agent=&quot;1&quot; world=&quot;10101&quot; name=&quot;agent_server&quot; private_ip=&quot;PRIVATE_IP&quot; private_port=&quot;51060&quot; public_ip =&quot;&quot; public_port=&quot;0&quot; public_udpport=&quot;0&quot; thread_num=2 session_count=10 debug=&quot;0&quot;/&gt;
        ///&lt;agentmanager ip=&quot;PRIVATE_IP&quot; port=&quot;51091&quot; code=&quot;900&quot; send_time_second=&quot;5&quot; /&gt;
        ///
        ///&lt;db_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51055&quot; code=&quot;1&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;db_log_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51056&quot; code=&quot;2&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;chat ip=&quot;PRIVATE_IP&quot; port=&quot;51057&quot; code=&quot;3&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;eme [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string agent_serveroption {
            get {
                return ResourceManager.GetString("agent_serveroption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server code=&quot;900&quot; agent=&quot;1&quot; world=&quot;10101&quot; name=&quot;agentmanager&quot; private_ip=&quot;PRIVATE_IP&quot; private_port=&quot;51091&quot; public_ip=&quot;PUBLIC_IP&quot; public_port=&quot;50091&quot; debug=&quot;0&quot;/&gt;
        ///&lt;agent_server ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; code=&quot;800&quot; /&gt;
        ///
        ///&lt;db_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51055&quot; code=&quot;1&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;db_log_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51056&quot; code=&quot;2&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;msg_server ip=&quot;PRIVATE_IP&quot; port=&quot;51052&quot; code=&quot;61&quot; /&gt;
        ///&lt;gm_server ip=&quot;PRIVATE_IP&quot; port=&quot;51002&quot; code=&quot;71&quot; /&gt;
        ///&lt;gate_server ip=&quot;PRI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AGENTMANAGER_900 {
            get {
                return ResourceManager.GetString("AGENTMANAGER_900", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server code=&quot;900&quot; agent=&quot;1&quot; world=&quot;10101&quot; name=&quot;agentmanager&quot; private_ip=&quot;PRIVATE_IP&quot; private_port=&quot;51091&quot; public_ip=&quot;PUBLIC_IP&quot; public_port=&quot;50091&quot; debug=&quot;0&quot;/&gt;
        ///&lt;agent_server ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; code=&quot;800&quot; /&gt;
        ///
        ///&lt;db_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51055&quot; code=&quot;1&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;db_log_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51056&quot; code=&quot;2&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;msg_server ip=&quot;PRIVATE_IP&quot; port=&quot;51052&quot; code=&quot;61&quot; /&gt;
        ///&lt;gm_server ip=&quot;PRIVATE_IP&quot; port=&quot;51002&quot; code=&quot;71&quot; /&gt;
        ///&lt;gate_server ip=&quot;PRI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string agentmanager_serveroption {
            get {
                return ResourceManager.GetString("agentmanager_serveroption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server code=&quot;101&quot; agent=&quot;1&quot; world=&quot;10101&quot; name=&quot;auction_server&quot; private_ip=&quot;PRIVATE_IP&quot; private_port=&quot;51053&quot; public_ip =&quot;&quot; public_port=&quot;0&quot; public_udpport=&quot;0&quot; debug=&quot;0&quot;/&gt;
        ///&lt;agent_server ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; code=&quot;800&quot; /&gt;
        ///
        ///&lt;agentmanager ip=&quot;PRIVATE_IP&quot; port=&quot;51091&quot; code=&quot;900&quot; send_time_second=&quot;5&quot; /&gt;
        ///&lt;db_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51055&quot; code=&quot;1&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;db_log_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51056&quot; code=&quot;2&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;msg_server ip=&quot;PRIVATE_IP&quot; port=&quot;51052&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AUCTION_101 {
            get {
                return ResourceManager.GetString("AUCTION_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server code=&quot;101&quot; agent=&quot;1&quot; world=&quot;10101&quot; name=&quot;auction_server&quot; private_ip=&quot;PRIVATE_IP&quot; private_port=&quot;51053&quot; public_ip =&quot;&quot; public_port=&quot;0&quot; public_udpport=&quot;0&quot; debug=&quot;0&quot;/&gt;
        ///&lt;agent_server ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; code=&quot;800&quot; /&gt;
        ///
        ///&lt;agentmanager ip=&quot;PRIVATE_IP&quot; port=&quot;51091&quot; code=&quot;900&quot; send_time_second=&quot;5&quot; /&gt;
        ///&lt;db_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51055&quot; code=&quot;1&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;db_log_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51056&quot; code=&quot;2&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;msg_server ip=&quot;PRIVATE_IP&quot; port=&quot;51052&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string auction_serveroption {
            get {
                return ResourceManager.GetString("auction_serveroption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///
        ///&lt;log_account string=&quot;Provider=SQLOLEDB;Password=SQL_DB_PASSWORD;User ID=SQL_DB_USER;Initial Catalog=RustyHearts_Log;Data Source=SQL_DB_SERVER&quot; timeout=&quot;5000&quot;/&gt;
        ///&lt;log_item string=&quot;Provider=SQLOLEDB;Password=SQL_DB_PASSWORD;User ID=SQL_DB_USER;Initial Catalog=RustyHearts_Log;Data Source=SQL_DB_SERVER&quot; timeout=&quot;5000&quot;/&gt;
        ///&lt;log_pet string=&quot;Provider=SQLOLEDB;Password=SQL_DB_PASSWORD;User ID=SQL_DB_USER;Initial Catalog=RustyHearts_Log;Data Source=SQL_DB_SERVER&quot; timeout=&quot;5000&quot;/&gt;
        ///&lt;log_loginout s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string customoption {
            get {
                return ResourceManager.GetString("customoption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server name=&quot;DBC_CHAT_3&quot; private_ip=&quot;PRIVATE_IP&quot; public_ip=&quot;&quot; code=&quot;3&quot; private_port=&quot;51057&quot; public_port=&quot;0&quot; public_udpport=&quot;0&quot; world=&quot;10101&quot; agent=&quot;1&quot; /&gt;
        ///&lt;dbc write_thread_count=&quot;3&quot; world=&quot;10101&quot;/&gt;
        ///&lt;agent_server ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; code=&quot;800&quot; /&gt;
        ///
        ///&lt;agentmanager ip=&quot;PRIVATE_IP&quot; port=&quot;51091&quot; code=&quot;900&quot; send_time_second=&quot;5&quot; /&gt;
        ///&lt;db_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51055&quot; code=&quot;1&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;msg_server ip=&quot;PRIVATE_IP&quot; port=&quot;51052&quot; code=&quot;61&quot; /&gt;
        ///&lt;gm_server ip=&quot;PRIVATE_IP&quot; port [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DBC_CHAT_3 {
            get {
                return ResourceManager.GetString("DBC_CHAT_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server name=&quot;DBC_EMERGENCY_4&quot; private_ip=&quot;PRIVATE_IP&quot; public_ip=&quot;&quot; code=&quot;4&quot; private_port=&quot;51058&quot; public_port=&quot;0&quot; public_udpport=&quot;0&quot; world=&quot;10101&quot; agent=&quot;1&quot; /&gt;
        ///&lt;dbc write_thread_count=&quot;3&quot; world=&quot;10101&quot;/&gt;
        ///&lt;agent_server ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; code=&quot;800&quot; /&gt;
        ///
        ///&lt;agentmanager ip=&quot;PRIVATE_IP&quot; port=&quot;51091&quot; code=&quot;900&quot; send_time_second=&quot;5&quot; /&gt;
        ///&lt;db_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51055&quot; code=&quot;1&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;msg_server ip=&quot;PRIVATE_IP&quot; port=&quot;51052&quot; code=&quot;61&quot; /&gt;
        ///&lt;gm_server ip=&quot;PRIVATE_IP&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DBC_EMERGENCY_4 {
            get {
                return ResourceManager.GetString("DBC_EMERGENCY_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server name=&quot;DBC_GAME_1&quot; private_ip=&quot;PRIVATE_IP&quot; public_ip=&quot;&quot; code=&quot;1&quot; private_port=&quot;51055&quot; public_port=&quot;0&quot; public_udpport=&quot;0&quot; world=&quot;10101&quot; agent=&quot;1&quot; /&gt;
        ///&lt;dbc write_thread_count=&quot;3&quot; world=&quot;10101&quot;/&gt;
        ///&lt;agent_server ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; code=&quot;800&quot; /&gt;
        ///
        ///&lt;agentmanager ip=&quot;PRIVATE_IP&quot; port=&quot;51091&quot; code=&quot;900&quot; send_time_second=&quot;5&quot; /&gt;
        ///&lt;db_log_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51056&quot; code=&quot;2&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;msg_server ip=&quot;PRIVATE_IP&quot; port=&quot;51052&quot; code=&quot;61&quot; /&gt;
        ///&lt;gm_server ip=&quot;PRIVATE_IP&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DBC_GAME_1 {
            get {
                return ResourceManager.GetString("DBC_GAME_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server name=&quot;DBC_LOG_2&quot; private_ip=&quot;PRIVATE_IP&quot; public_ip=&quot;&quot; code=&quot;2&quot; private_port=&quot;51056&quot; public_port=&quot;0&quot; public_udpport=&quot;0&quot; world=&quot;10101&quot; agent=&quot;1&quot; /&gt;
        ///&lt;dbc write_thread_count=&quot;3&quot; world=&quot;10101&quot;/&gt;
        ///&lt;agent_server ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; code=&quot;800&quot; /&gt;
        ///
        ///
        ///&lt;db_account string=&quot;Provider=SQLOLEDB;Password=SQL_DB_PASSWORD;User ID=SQL_DB_USER;Initial Catalog=RustyHearts_Auth;Data Source=SQL_DB_SERVER&quot; timeout=&quot;5000&quot;/&gt;
        ///&lt;db_web string=&quot;Provider=SQLOLEDB;Password=SQL_DB_PASSWORD;User ID=SQL_D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DBC_LOG_2 {
            get {
                return ResourceManager.GetString("DBC_LOG_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server name=&quot;DBC_GAME_1&quot; private_ip=&quot;PRIVATE_IP&quot; public_ip=&quot;&quot; code=&quot;1&quot; private_port=&quot;51055&quot; public_port=&quot;0&quot; public_udpport=&quot;0&quot; world=&quot;10101&quot; agent=&quot;1&quot; /&gt;
        ///&lt;dbc write_thread_count=&quot;3&quot; world=&quot;10101&quot;/&gt;
        ///&lt;agent_server ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; code=&quot;800&quot; /&gt;
        ///
        ///
        ///&lt;db_account string=&quot;Provider=SQLOLEDB;Password=SQL_DB_PASSWORD;User ID=SQL_DB_USER;Initial Catalog=RustyHearts_Auth;Data Source=SQL_DB_SERVER&quot; timeout=&quot;5000&quot;/&gt;
        ///&lt;db_web string=&quot;Provider=SQLOLEDB;Password=SQL_DB_PASSWORD;User ID=SQL_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dbc_serveroption {
            get {
                return ResourceManager.GetString("dbc_serveroption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///
        ///&lt;server code=&quot;2&quot; agent=&quot;1&quot; world=&quot;10101&quot; name=&quot;db_log_cache&quot; private_ip=&quot;PRIVATE_IP&quot; private_port=&quot;51056&quot; debug=&quot;0&quot;/&gt;
        ///&lt;dbc write_thread_count=&quot;8&quot; /&gt;
        ///&lt;agent_server ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; code=&quot;800&quot; /&gt;
        ///
        ///&lt;agentmanager ip=&quot;PRIVATE_IP&quot; port=&quot;51091&quot; code=&quot;900&quot; send_time_second=&quot;5&quot; /&gt;
        ///&lt;db_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51055&quot; code=&quot;1&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;msg_server ip=&quot;PRIVATE_IP&quot; port=&quot;51052&quot; code=&quot;61&quot; /&gt;
        ///&lt;gm_server ip=&quot;PRIVATE_IP&quot; port=&quot;51002&quot; code=&quot;71&quot; /&gt;
        ///&lt;gate_server ip=&quot;PRIVATE_IP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dbc_serveroptionlog {
            get {
                return ResourceManager.GetString("dbc_serveroptionlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server name=&quot;DUNGEON_2001&quot; private_ip=&quot;&quot; public_ip=&quot;PUBLIC_IP&quot; code=&quot;2001&quot; private_port=&quot;0&quot; public_port=&quot;50016&quot; public_udpport=&quot;0&quot; world=&quot;10101&quot; agent=&quot;1&quot; /&gt;
        ///&lt;develop preload=&quot;1&quot; preload_char=&quot;1&quot; /&gt;
        ///&lt;agent_server ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; code=&quot;800&quot; /&gt;
        ///
        ///&lt;agentmanager ip=&quot;PRIVATE_IP&quot; port=&quot;51091&quot; code=&quot;900&quot; send_time_second=&quot;5&quot; /&gt;
        ///&lt;db_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51055&quot; code=&quot;1&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;db_log_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51056&quot; code=&quot;2&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;msg_server [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DUNGEON_2001 {
            get {
                return ResourceManager.GetString("DUNGEON_2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server code=&quot;2001&quot; agent=&quot;1&quot; world=&quot;10101&quot; name=&quot;dungeon_server&quot; private_ip=&quot;&quot; private_port=&quot;0&quot; public_ip=&quot;PUBLIC_IP&quot; public_port=&quot;50016&quot; debug=&quot;0&quot;/&gt;
        ///&lt;develop preload=&quot;1&quot; preload_char=&quot;1&quot; /&gt;
        ///&lt;agent_server ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; code=&quot;800&quot; /&gt;
        ///
        ///&lt;agentmanager ip=&quot;PRIVATE_IP&quot; port=&quot;51091&quot; code=&quot;900&quot; send_time_second=&quot;5&quot; /&gt;
        ///&lt;db_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51055&quot; code=&quot;1&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;db_log_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51056&quot; code=&quot;2&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;msg_server ip=&quot;PRI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dungeon_serveroption {
            get {
                return ResourceManager.GetString("dungeon_serveroption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] env {
            get {
                object obj = ResourceManager.GetObject("env", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string game_gateserver_list {
            get {
                return ResourceManager.GetString("game_gateserver_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server code=&quot;21001&quot; agent=&quot;21001&quot; world=&quot;10101&quot; name=&quot;lobby_server&quot; private_ip=&quot;PRIVATE_IP&quot; private_port=&quot;51006&quot; public_ip =&quot;PUBLIC_IP&quot; public_port=&quot;50006&quot; public_udpport=&quot;0&quot; thread_num=2 session_count=10 debug=&quot;0&quot;/&gt;
        ///&lt;agent_server ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; code=&quot;800&quot; /&gt;
        ///
        ///&lt;agentmanager ip=&quot;PRIVATE_IP&quot; port=&quot;51091&quot; code=&quot;900&quot; send_time_second=&quot;5&quot; /&gt;
        ///&lt;db_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51055&quot; code=&quot;1&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;db_log_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51056&quot; code=&quot;2&quot; session_count= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string game_serveroption {
            get {
                return ResourceManager.GetString("game_serveroption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server code=&quot;81&quot; agent=&quot;1&quot; world=&quot;10101&quot; name=&quot;GATE_81&quot; private_ip=&quot;PRIVATE_IP&quot; private_port=&quot;50008&quot; public_ip =&quot;PUBLIC_IP&quot; public_port=&quot;50001&quot; public_udpport=&quot;0&quot; debug=&quot;0&quot;/&gt;
        ///&lt;dbc write_thread_count=&quot;3&quot; world=&quot;10101&quot;/&gt;
        ///&lt;auto /&gt;
        ///&lt;agent_server ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; code=&quot;800&quot; /&gt;
        ///
        ///&lt;agentmanager ip=&quot;PRIVATE_IP&quot; port=&quot;51091&quot; code=&quot;900&quot; send_time_second=&quot;5&quot; /&gt;
        ///&lt;db_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51055&quot; code=&quot;1&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;db_log_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51056&quot; code=&quot;2&quot; ses [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GATE_81 {
            get {
                return ResourceManager.GetString("GATE_81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server code=&quot;81&quot; agent=&quot;1&quot; world=&quot;10101&quot; name=&quot;gate_server&quot; private_ip=&quot;PRIVATE_IP&quot; private_port=&quot;50008&quot; public_ip =&quot;PUBLIC_IP&quot; public_port=&quot;50001&quot; public_udpport=&quot;0&quot; debug=&quot;0&quot;/&gt;
        ///&lt;dbc write_thread_count=&quot;3&quot; world=&quot;10101&quot;/&gt;
        ///&lt;auto /&gt;
        ///&lt;agent_server ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; code=&quot;800&quot; /&gt;
        ///
        ///&lt;agentmanager ip=&quot;PRIVATE_IP&quot; port=&quot;51091&quot; code=&quot;900&quot; send_time_second=&quot;5&quot; /&gt;
        ///&lt;db_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51055&quot; code=&quot;1&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;db_log_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51056&quot; code=&quot;2&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gate_serveroption {
            get {
                return ResourceManager.GetString("gate_serveroption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server name=&quot;GM_71&quot; private_ip=&quot;PRIVATE_IP&quot; public_ip=&quot;PUBLIC_IP&quot; code=&quot;71&quot; private_port=&quot;51002&quot; public_port=&quot;50002&quot; public_udpport=&quot;0&quot; world=&quot;10101&quot; agent=&quot;1&quot; /&gt;
        ///&lt;agent_server ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; code=&quot;800&quot; /&gt;
        ///
        ///&lt;agentmanager ip=&quot;PRIVATE_IP&quot; port=&quot;51091&quot; code=&quot;900&quot; send_time_second=&quot;5&quot; /&gt;
        ///&lt;db_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51055&quot; code=&quot;1&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;db_log_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51056&quot; code=&quot;2&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;msg_server ip=&quot;PRIVATE_IP&quot; port=&quot;51052&quot; code=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GM_71 {
            get {
                return ResourceManager.GetString("GM_71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server code=&quot;71&quot; agent=&quot;1&quot; world=&quot;10101&quot; name=&quot;gm_server&quot; private_ip=&quot;PRIVATE_IP&quot; private_port=&quot;51002&quot; public_ip =&quot;PUBLIC_IP&quot; public_port=&quot;50002&quot; public_udpport=&quot;0&quot; debug=&quot;0&quot;/&gt;
        ///&lt;agent_server ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; code=&quot;800&quot; /&gt;
        ///
        ///&lt;agentmanager ip=&quot;PRIVATE_IP&quot; port=&quot;51091&quot; code=&quot;900&quot; send_time_second=&quot;5&quot; /&gt;
        ///&lt;db_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51055&quot; code=&quot;1&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;db_log_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51056&quot; code=&quot;2&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;msg_server ip=&quot;PRIVATE_IP&quot; port= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gm_serveroption {
            get {
                return ResourceManager.GetString("gm_serveroption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server name=&quot;GUILD_5001&quot; private_ip=&quot;PRIVATE_IP&quot; public_ip=&quot;PUBLIC_IP&quot; code=&quot;5001&quot; private_port=&quot;51003&quot; public_port=&quot;50003&quot; public_udpport=&quot;0&quot; world=&quot;10101&quot; agent=&quot;1&quot; /&gt;
        ///&lt;guildlobby value=&quot;1&quot; /&gt;
        ///&lt;agent_server ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; code=&quot;800&quot; /&gt;
        ///
        ///&lt;agentmanager ip=&quot;PRIVATE_IP&quot; port=&quot;51091&quot; code=&quot;900&quot; send_time_second=&quot;5&quot; /&gt;
        ///&lt;db_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51055&quot; code=&quot;1&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;db_log_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51056&quot; code=&quot;2&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;msg_server ip= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GUILD_5001 {
            get {
                return ResourceManager.GetString("GUILD_5001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server code=&quot;5001&quot; agent=&quot;1&quot; world=&quot;10101&quot; name=&quot;guild_server&quot; private_ip=&quot;PRIVATE_IP&quot; private_port=&quot;51003&quot; public_ip =&quot;PUBLIC_IP&quot; public_port=&quot;50003&quot; public_udpport=&quot;0&quot; debug=&quot;0&quot;/&gt;
        ///&lt;guildlobby value=&quot;1&quot; /&gt;
        ///&lt;agent_server ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; code=&quot;800&quot; /&gt;
        ///
        ///&lt;agentmanager ip=&quot;PRIVATE_IP&quot; port=&quot;51091&quot; code=&quot;900&quot; send_time_second=&quot;5&quot; /&gt;
        ///&lt;db_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51055&quot; code=&quot;1&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;db_log_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51056&quot; code=&quot;2&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;ms [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string guild_serveroption {
            get {
                return ResourceManager.GetString("guild_serveroption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_browse_folder_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-browse-folder-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_database_export_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-database-export-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_database_restore_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-database-restore-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_edit_file_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-edit-file-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_ethernet_on_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-ethernet-on-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_eye_16 {
            get {
                object obj = ResourceManager.GetObject("icons8-eye-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_globe_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-globe-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_log_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-log-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_login_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-login-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_opened_folder_16 {
            get {
                object obj = ResourceManager.GetObject("icons8-opened-folder-16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_opened_folder_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-opened-folder-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_opened_folder_48 {
            get {
                object obj = ResourceManager.GetObject("icons8-opened-folder-48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_password_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-password-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_play_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-play-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_save_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-save-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_shutdown_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-shutdown-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_sql_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-sql-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_user_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-user-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_web_address_32 {
            get {
                object obj = ResourceManager.GetObject("icons8-web-address-32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server name=&quot;LOBBY_21001&quot; private_ip=&quot;PRIVATE_IP&quot; public_ip=&quot;PUBLIC_IP&quot; code=&quot;21001&quot; private_port=&quot;51006&quot; public_port=&quot;50006&quot; public_udpport=&quot;0&quot; world=&quot;10101&quot; agent=&quot;1&quot; /&gt;
        ///&lt;agent_server ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; code=&quot;800&quot; /&gt;
        ///
        ///&lt;agentmanager ip=&quot;PRIVATE_IP&quot; port=&quot;51091&quot; code=&quot;900&quot; send_time_second=&quot;5&quot; /&gt;
        ///&lt;db_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51055&quot; code=&quot;1&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;db_log_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51056&quot; code=&quot;2&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;msg_server ip=&quot;PRIVATE_IP&quot; port=&quot;5105 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LOBBY_21001 {
            get {
                return ResourceManager.GetString("LOBBY_21001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server code=&quot;21001&quot; agent=&quot;1&quot; world=&quot;10101&quot; name=&quot;lobby_server&quot; private_ip=&quot;PRIVATE_IP&quot; private_port=&quot;51006&quot; public_ip =&quot;PUBLIC_IP&quot; public_port=&quot;50006&quot; public_udpport=&quot;0&quot; thread_num=2 session_count=10 debug=&quot;0&quot;/&gt;
        ///&lt;agent_server ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; code=&quot;800&quot; /&gt;
        ///
        ///&lt;agentmanager ip=&quot;PRIVATE_IP&quot; port=&quot;51091&quot; code=&quot;900&quot; send_time_second=&quot;5&quot; /&gt;
        ///&lt;db_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51055&quot; code=&quot;1&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;db_log_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51056&quot; code=&quot;2&quot; session_count=&quot;5&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string lobby_serveroption {
            get {
                return ResourceManager.GetString("lobby_serveroption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///
        ///&lt;log&gt;
        ///	&lt;log_type use=&quot;1&quot; id=&quot;0&quot; name = &quot;LOG_CONNECTION&quot; /&gt;
        ///	&lt;log_type use=&quot;1&quot; id=&quot;1&quot; name = &quot;LOG_SRV_SELECT&quot; /&gt;
        ///	&lt;log_type use=&quot;1&quot; id=&quot;2&quot; name = &quot;LOG_CH_SELECT&quot; /&gt;
        ///	&lt;log_type use=&quot;1&quot; id=&quot;3&quot; name = &quot;LOG_IN_OUT&quot; /&gt;
        ///	&lt;log_type use=&quot;1&quot; id=&quot;4&quot; name = &quot;LOG_PLAY_TIME&quot; /&gt;
        ///	&lt;log_type use=&quot;1&quot; id=&quot;5&quot; name = &quot;LOG_DUNGEON_CLEAR&quot; /&gt;
        ///	&lt;log_type use=&quot;1&quot; id=&quot;6&quot; name = &quot;LOG_LEVEL_UP&quot; /&gt;
        ///	&lt;log_type use=&quot;1&quot; id=&quot;7&quot; name = &quot;LOG_CHAR_IN&quot; /&gt;
        ///	&lt;log_type use=&quot;1&quot; id=&quot;8&quot; name = &quot;LOG_CHAR_IN_DUNGEON&quot; /&gt;
        ///	&lt;log_ty [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string log_control {
            get {
                return ResourceManager.GetString("log_control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server name=&quot;MANAGER_91&quot; private_ip=&quot;PRIVATE_IP&quot; public_ip=&quot;&quot; code=&quot;91&quot; private_port=&quot;51051&quot; public_port=&quot;0&quot; public_udpport=&quot;0&quot; world=&quot;10101&quot; agent=&quot;1&quot; /&gt;
        ///&lt;agent_server ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; code=&quot;800&quot; /&gt;
        ///
        ///&lt;agentmanager ip=&quot;PRIVATE_IP&quot; port=&quot;51091&quot; code=&quot;900&quot; send_time_second=&quot;5&quot; /&gt;
        ///&lt;db_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51055&quot; code=&quot;1&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;db_log_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51056&quot; code=&quot;2&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;msg_server ip=&quot;PRIVATE_IP&quot; port=&quot;51052&quot; code=&quot;61&quot; /&gt;
        ///&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MANAGER_91 {
            get {
                return ResourceManager.GetString("MANAGER_91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server code=&quot;91&quot; agent=&quot;1&quot; world=&quot;10101&quot; name=&quot;manager_server&quot; private_ip=&quot;PRIVATE_IP&quot; private_port=&quot;51051&quot; public_ip =&quot;&quot; public_port=&quot;0&quot; public_udpport=&quot;0&quot; debug=&quot;0&quot;/&gt;
        ///&lt;agent_server ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; code=&quot;800&quot; /&gt;
        ///
        ///&lt;agentmanager ip=&quot;PRIVATE_IP&quot; port=&quot;51091&quot; code=&quot;900&quot; send_time_second=&quot;5&quot; /&gt;
        ///&lt;db_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51055&quot; code=&quot;1&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;db_log_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51056&quot; code=&quot;2&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;msg_server ip=&quot;PRIVATE_IP&quot; port=&quot;51052&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string manager_serveroption {
            get {
                return ResourceManager.GetString("manager_serveroption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server name=&quot;MATCH_111&quot; private_ip=&quot;PRIVATE_IP&quot; public_ip=&quot;&quot; code=&quot;111&quot; private_port=&quot;51054&quot; public_port=&quot;0&quot; public_udpport=&quot;0&quot; world=&quot;10101&quot; agent=&quot;1&quot; /&gt;
        ///&lt;agent_server ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; code=&quot;800&quot; /&gt;
        ///
        ///&lt;agentmanager ip=&quot;PRIVATE_IP&quot; port=&quot;51091&quot; code=&quot;900&quot; send_time_second=&quot;5&quot; /&gt;
        ///&lt;db_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51055&quot; code=&quot;1&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;db_log_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51056&quot; code=&quot;2&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;msg_server ip=&quot;PRIVATE_IP&quot; port=&quot;51052&quot; code=&quot;61&quot; /&gt;
        ///&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MATCH_111 {
            get {
                return ResourceManager.GetString("MATCH_111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server code=&quot;111&quot; agent=&quot;1&quot; world=&quot;10101&quot; name=&quot;match_server&quot; private_ip=&quot;PRIVATE_IP&quot; private_port=&quot;51054&quot; public_ip =&quot;&quot; public_port=&quot;0&quot; public_udpport=&quot;0&quot; debug=&quot;0&quot;/&gt;
        ///&lt;agent_server ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; code=&quot;800&quot; /&gt;
        ///
        ///&lt;agentmanager ip=&quot;PRIVATE_IP&quot; port=&quot;51091&quot; code=&quot;900&quot; send_time_second=&quot;5&quot; /&gt;
        ///&lt;db_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51055&quot; code=&quot;1&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;db_log_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51056&quot; code=&quot;2&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;msg_server ip=&quot;PRIVATE_IP&quot; port=&quot;51052&quot; c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string match_serveroption {
            get {
                return ResourceManager.GetString("match_serveroption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server name=&quot;MSG_61&quot; private_ip=&quot;PRIVATE_IP&quot; public_ip=&quot;&quot; code=&quot;61&quot; private_port=&quot;51052&quot; public_port=&quot;0&quot; public_udpport=&quot;0&quot; world=&quot;10101&quot; agent=&quot;1&quot; /&gt;
        ///&lt;agent_server ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; code=&quot;800&quot; /&gt;
        ///
        ///&lt;agentmanager ip=&quot;PRIVATE_IP&quot; port=&quot;51091&quot; code=&quot;900&quot; send_time_second=&quot;5&quot; /&gt;
        ///&lt;db_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51055&quot; code=&quot;1&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;db_log_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51056&quot; code=&quot;2&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;gm_server ip=&quot;PRIVATE_IP&quot; port=&quot;51002&quot; code=&quot;71&quot; /&gt;
        ///&lt;gate_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MSG_61 {
            get {
                return ResourceManager.GetString("MSG_61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server code=&quot;61&quot; agent=&quot;1&quot; world=&quot;10101&quot; name=&quot;msg_server&quot; private_ip=&quot;PRIVATE_IP&quot; private_port=&quot;51052&quot; public_ip =&quot;&quot; public_port=&quot;0&quot; public_udpport=&quot;0&quot; debug=&quot;0&quot;/&gt;
        ///&lt;agent_server ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; code=&quot;800&quot; /&gt;
        ///
        ///&lt;agentmanager ip=&quot;PRIVATE_IP&quot; port=&quot;51091&quot; code=&quot;900&quot; send_time_second=&quot;5&quot; /&gt;
        ///&lt;db_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51055&quot; code=&quot;1&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;db_log_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51056&quot; code=&quot;2&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;gm_server ip=&quot;PRIVATE_IP&quot; port=&quot;51002&quot; code= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string msg_serveroption {
            get {
                return ResourceManager.GetString("msg_serveroption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///
        ///.
        /// </summary>
        internal static string patch {
            get {
                return ResourceManager.GetString("patch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server name=&quot;PVP_3003&quot; private_ip=&quot;&quot; public_ip=&quot;PUBLIC_IP&quot; code=&quot;3003&quot; private_port=&quot;0&quot; public_port=&quot;50004&quot; public_udpport=&quot;52000&quot; world=&quot;10101&quot; udp_count=&quot;50&quot; agent=&quot;1&quot; /&gt;
        ///&lt;pvp value=&quot;50&quot; /&gt;
        ///&lt;agent_server ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; code=&quot;800&quot; /&gt;
        ///
        ///&lt;agentmanager ip=&quot;PRIVATE_IP&quot; port=&quot;51091&quot; code=&quot;900&quot; send_time_second=&quot;5&quot; /&gt;
        ///&lt;db_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51055&quot; code=&quot;1&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;db_log_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51056&quot; code=&quot;2&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;msg_server ip=&quot;PR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PVP_3003 {
            get {
                return ResourceManager.GetString("PVP_3003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server code=&quot;3003&quot; agent=&quot;1&quot; world=&quot;10101&quot; name=&quot;pvp_server&quot; private_ip=&quot;&quot; private_port=&quot;0&quot; public_ip =&quot;PUBLIC_IP&quot; public_port=&quot;50004&quot; public_udpport=&quot;52000&quot; public_updcount=&quot;50&quot; debug=&quot;0&quot;/&gt;
        ///&lt;pvp value=&quot;50&quot; /&gt;
        ///&lt;agent_server ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; code=&quot;800&quot; /&gt;
        ///
        ///&lt;agentmanager ip=&quot;PRIVATE_IP&quot; port=&quot;51091&quot; code=&quot;900&quot; send_time_second=&quot;5&quot; /&gt;
        ///&lt;db_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51055&quot; code=&quot;1&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;db_log_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51056&quot; code=&quot;2&quot; session_count=&quot;5&quot; /&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string pvp_serveroption {
            get {
                return ResourceManager.GetString("pvp_serveroption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
        ///// DBC Server
        /////=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
        ///
        ///[DBC SERVER]
        ///ip = PRIVATE_IP
        ///port = 51055
        ///max connection = 100
        ///
        /////=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
        ///// Auth Database
        /////=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
        ///
        ///[AUTH DATABASE]
        ///Account DB Connection String = Provider=SQLOLEDB;Passwo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string server_info {
            get {
                return ResourceManager.GetString("server_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///&lt;server code=&quot;21001&quot; agent=&quot;1&quot; world=&quot;10101&quot; name=&quot;lobby_server&quot; private_ip=&quot;PRIVATE_IP&quot; private_port=&quot;51006&quot; public_ip =&quot;PUBLIC_IP&quot; public_port=&quot;50006&quot; public_udpport=&quot;0&quot; thread_num=2 session_count=10 debug=&quot;0&quot;/&gt;
        ///
        ///&lt;agent_server ip=&quot;PRIVATE_IP&quot; port=&quot;51060&quot; code=&quot;800&quot; /&gt;
        ///
        ///&lt;agentmanager ip=&quot;PRIVATE_IP&quot; port=&quot;51091&quot; code=&quot;900&quot; send_time_second=&quot;5&quot; /&gt;
        ///&lt;db_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51055&quot; code=&quot;1&quot; session_count=&quot;5&quot; /&gt;
        ///&lt;db_log_cache ip=&quot;PRIVATE_IP&quot; port=&quot;51056&quot; code=&quot;2&quot; session_count=&quot;5&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string serveroption {
            get {
                return ResourceManager.GetString("serveroption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;
        ///
        ///&lt;service&gt;
        ///	&lt;active_area country=&quot;SERVICE_COUNTRY&quot; /&gt;
        ///	
        ///	&lt;area country=&quot;usa&quot; auth_url=&quot;AUTH_URL&quot; billing_url=&quot;BILLING_URL&quot; skip_auth=&quot;SKIP_AUTH&quot; skip_billing=&quot;SKIP_BILLING&quot; free_cash=&quot;FREE_CASH&quot; skip_abuse_nick=&quot;SKIP_ABUSE_NICK&quot; channel_limit_count=&quot;CHANNEL_LIMIT_COUNT&quot; world_user_limit_count=&quot;WORLD_USER_LIMIT_COUNT&quot; second_pass=&quot;SECOND_PASS&quot; billing_idc=&quot;10101&quot; xtrap_use=&quot;0&quot; server_mode=&quot;SERVER_MODE&quot; betazone=&quot;BETAZONE&quot; /&gt;
        ///	
        ///	&lt;area country=&quot;jpn&quot; auth_url=&quot;AUTH_URL&quot; billing_url=&quot;BILLI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string service_control {
            get {
                return ResourceManager.GetString("service_control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;.
        /// </summary>
        internal static string shop_control {
            get {
                return ResourceManager.GetString("shop_control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; ?&gt;.
        /// </summary>
        internal static string total_option {
            get {
                return ResourceManager.GetString("total_option", resourceCulture);
            }
        }
    }
}
